package com.valley.cws.entity;
// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WcaAdShownHistory generated by hbm2java
 */
@Entity
@Table(name = "WCA_AD_SHOWN_HISTORY")
public class WcaAdShownHistory implements java.io.Serializable {

	private static final long serialVersionUID = 5784771882292270288L;
	private Long id;
	private WcaUserProfile wcaUserProfile;
	private WcaAdData wcaAdData;
	private String macAddress;
	private Integer freeMinutes;
	private Integer rating;
	private Date createdOn;
	private String opinion;

	@Column(name = "opinion", length = 19)
	        public String getOpinion() {
	                return opinion;
	        }

	        public void setOpinion(String opinion) {
	                this.opinion = opinion;
	        }

	public WcaAdShownHistory() {
	}

	public WcaAdShownHistory(WcaUserProfile wcaUserProfile, WcaAdData wcaAdData) {
		this.wcaUserProfile = wcaUserProfile;
		this.wcaAdData = wcaAdData;
	}

	public WcaAdShownHistory(WcaUserProfile wcaUserProfile, WcaAdData wcaAdData, Date createdOn) {
		this.wcaUserProfile = wcaUserProfile;
		this.wcaAdData = wcaAdData;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	//@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_AD_SHWN_HSTRY_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public WcaUserProfile getWcaUserProfile() {
		return this.wcaUserProfile;
	}

	public void setWcaUserProfile(WcaUserProfile wcaUserProfile) {
		this.wcaUserProfile = wcaUserProfile;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ad_id", nullable = false)
	public WcaAdData getWcaAdData() {
		return this.wcaAdData;
	}

	public void setWcaAdData(WcaAdData wcaAdData) {
		this.wcaAdData = wcaAdData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	@Column(name = "free_minutes", length = 19)
	public Integer getFreeMinutes() {
		return freeMinutes;
	}

	public void setFreeMinutes(Integer freeMinutes) {
		this.freeMinutes = freeMinutes;
	}

	@Column(name = "mac_address", length = 45)
	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}
	@Column(name = "rating", length = 11)
	public Integer getRating() {
		return rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

}
