package com.valley.cws.entity;

// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * WcaAdData generated by hbm2java
 */
@Entity
@Table(name = "WCA_AD_DATA")
public class WcaAdData implements java.io.Serializable {
	private static final long serialVersionUID = -2676796573316635094L;
	private Long id;
	private WcaCategoryDetails wcaCategoryDetails;
	private WcaSubcategoryDetails wcaSubcategoryDetails;
	private String filePath;
	private String filePath1;
	private String filePath2;
	private String name;
	private Integer duration;
	private String adsType;
	private Integer likeCount;
	private Integer dislikeCount;
	private Integer rateCount;
	private Integer totalRateCount;
	private Integer point;
	private Boolean isActive;
	private Integer screenType;
	private String redirectUrl;
	private Set<WcaAdShownHistory> wcaAdShownHistories = new HashSet<WcaAdShownHistory>(0);
	private Set<WcaPolicyAdConfiguration> wcaPolicyAdConfigurations = new HashSet<WcaPolicyAdConfiguration>(0);

	public WcaAdData() {
	}

	public WcaAdData(WcaCategoryDetails wcaCategoryDetails, String name) {
		this.wcaCategoryDetails = wcaCategoryDetails;
		this.name = name;
	}

	public WcaAdData(Long id, WcaCategoryDetails wcaCategoryDetails, WcaSubcategoryDetails wcaSubcategoryDetails, String filePath,
			String filePath1, String filePath2, String name, Integer duration, String adsType, Integer likeCount, Integer dislikeCount,
			Integer rateCount, Integer totalRateCount, Integer point, Boolean isActive, Integer screenType, String redirectUrl,
			Set<WcaAdShownHistory> wcaAdShownHistories, Set<WcaPolicyAdConfiguration> wcaPolicyAdConfigurations) {
		super();
		this.id = id;
		this.wcaCategoryDetails = wcaCategoryDetails;
		this.wcaSubcategoryDetails = wcaSubcategoryDetails;
		this.filePath = filePath;
		this.filePath1 = filePath1;
		this.filePath2 = filePath2;
		this.name = name;
		this.duration = duration;
		this.adsType = adsType;
		this.likeCount = likeCount;
		this.dislikeCount = dislikeCount;
		this.rateCount = rateCount;
		this.totalRateCount = totalRateCount;
		this.point = point;
		this.isActive = isActive;
		this.screenType = screenType;
		this.redirectUrl = redirectUrl;
		this.wcaAdShownHistories = wcaAdShownHistories;
		this.wcaPolicyAdConfigurations = wcaPolicyAdConfigurations;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	//@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_AD_DATA_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	@JsonIgnore
	public WcaCategoryDetails getWcaCategoryDetails() {
		return this.wcaCategoryDetails;
	}

	public void setWcaCategoryDetails(WcaCategoryDetails wcaCategoryDetails) {
		this.wcaCategoryDetails = wcaCategoryDetails;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "subcategory_id")
	@JsonIgnore
	public WcaSubcategoryDetails getWcaSubcategoryDetails() {
		return this.wcaSubcategoryDetails;
	}

	public void setWcaSubcategoryDetails(WcaSubcategoryDetails wcaSubcategoryDetails) {
		this.wcaSubcategoryDetails = wcaSubcategoryDetails;
	}

	@Column(name = "file_path", length = 255)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "file_path1")
	public String getFilePath1() {
		return filePath1;
	}

	public void setFilePath1(String filePath1) {
		this.filePath1 = filePath1;
	}

	@Column(name = "file_path2")
	public String getFilePath2() {
		return filePath2;
	}

	public void setFilePath2(String filePath2) {
		this.filePath2 = filePath2;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "duration", length = 19)
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "ads_type", length = 45)
	public String getAdsType() {
		return this.adsType;
	}

	public void setAdsType(String adsType) {
		this.adsType = adsType;
	}

	@Column(name = "like_count")
	public Integer getLikeCount() {
		return likeCount;
	}

	public void setLikeCount(Integer likeCount) {
		this.likeCount = likeCount;
	}

	@Column(name = "dislike_count")
	public Integer getDislikeCount() {
		return dislikeCount;
	}

	public void setDislikeCount(Integer dislikeCount) {
		this.dislikeCount = dislikeCount;
	}

	@Column(name = "rate_count")
	public Integer getRateCount() {
		return rateCount;
	}

	public void setRateCount(Integer rateCount) {
		this.rateCount = rateCount;
	}

	@Column(name = "point")
	public Integer getPoint() {
		return point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Column(name = "totalrate_count")
	public Integer getTotalRateCount() {
		return totalRateCount;
	}

	public void setTotalRateCount(Integer totalRateCount) {
		this.totalRateCount = totalRateCount;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "screen_type", length = 19)
	public Integer getScreenType() {
		return screenType;
	}

	public void setScreenType(Integer screenType) {
		this.screenType = screenType;
	}

	@Column(name = "redirect_url")
	public String getRedirectUrl() {
	return redirectUrl;
	}

	public void setRedirectUrl(String redirectUrl) {
	this.redirectUrl = redirectUrl;
	} 
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaAdData")
	@JsonIgnore
	public Set<WcaAdShownHistory> getWcaAdShownHistories() {
		return this.wcaAdShownHistories;
	}

	public void setWcaAdShownHistories(Set<WcaAdShownHistory> wcaAdShownHistories) {
		this.wcaAdShownHistories = wcaAdShownHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaAdData")
	@JsonIgnore
	public Set<WcaPolicyAdConfiguration> getWcaPolicyAdConfigurations() {
		return this.wcaPolicyAdConfigurations;
	}

	public void setWcaPolicyAdConfigurations(Set<WcaPolicyAdConfiguration> wcaPolicyAdConfigurations) {
		this.wcaPolicyAdConfigurations = wcaPolicyAdConfigurations;
	}

}
