package com.valley.cws.entity;
// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WcaBuyingHistory generated by hbm2java
 */
@Entity
@Table(name = "WCA_BUYING_HISTORY")
public class WcaBuyingHistory implements java.io.Serializable {

	private static final long serialVersionUID = -2309192538474627379L;
	private Integer id;
	private WcaUserProfile wcaUserProfile;
	private WcaWalletPlan wcaWalletPlan;
	private String bankName;
	private String bankTxnId;
	private String currency;
	private String gatewayName;
	private String mId;
	private String orderId;
	private String paymentMode;
	private String responseCode;
	private String responseMsg;
	private String status;
	private Double txnAmount;
	private Date txnDate;
	private String txnId;
	private Date txnInitiateTime;
	private Date txnCompletionTime;
	private Date createdOn;

	public WcaBuyingHistory() {
	}

	public WcaBuyingHistory(Integer id, WcaUserProfile wcaUserProfile, WcaWalletPlan wcaWalletPlan, String bankName, String bankTxnId,
			String currency, String gatewayName, String mId, String orderId, String paymentMode, String responseCode, String responseMsg,
			String status, Double txnAmount, Date txnDate, String txnId, Date txnInitiateTime, Date txnCompletionTime, Date createdOn) {
		super();
		this.id = id;
		this.wcaUserProfile = wcaUserProfile;
		this.wcaWalletPlan = wcaWalletPlan;
		this.bankName = bankName;
		this.bankTxnId = bankTxnId;
		this.currency = currency;
		this.gatewayName = gatewayName;
		this.mId = mId;
		this.orderId = orderId;
		this.paymentMode = paymentMode;
		this.responseCode = responseCode;
		this.responseMsg = responseMsg;
		this.status = status;
		this.txnAmount = txnAmount;
		this.txnDate = txnDate;
		this.txnId = txnId;
		this.txnInitiateTime = txnInitiateTime;
		this.txnCompletionTime = txnCompletionTime;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_AD_DATA_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public WcaUserProfile getWcaUserProfile() {
		return this.wcaUserProfile;
	}

	public void setWcaUserProfile(WcaUserProfile wcaUserProfile) {
		this.wcaUserProfile = wcaUserProfile;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pack_id", nullable = false)
	public WcaWalletPlan getWcaWalletPlan() {
		return wcaWalletPlan;
	}

	public void setWcaWalletPlan(WcaWalletPlan wcaWalletPlan) {
		this.wcaWalletPlan = wcaWalletPlan;
	}
	
	
	@Column(name = "bank_name")
	public String getBankName() {
		return bankName;
	}
	
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	
	@Column(name = "bank_txn_id")
	public String getBankTxnId() {
		return bankTxnId;
	}

	public void setBankTxnId(String bankTxnId) {
		this.bankTxnId = bankTxnId;
	}

	@Column(name = "currency")
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}


	@Column(name = "gateway_name")
	public String getGatewayName() {
		return gatewayName;
	}
	
	public void setGatewayName(String gatewayName) {
		this.gatewayName = gatewayName;
	}

	@Column(name = "mid")
	public String getmId() {
		return mId;
	}

	public void setmId(String mId) {
		this.mId = mId;
	}

	@Column(name = "order_id")
	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "payment_mode")
	public String getPaymentMode() {
		return paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "response_code")
	public String getResponseCode() {
		return responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "response_msg")
	public String getResponseMsg() {
		return responseMsg;
	}

	public void setResponseMsg(String responseMsg) {
		this.responseMsg = responseMsg;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "txn_amount")
	public Double getTxnAmount() {
		return txnAmount;
	}

	public void setTxnAmount(Double txnAmount) {
		this.txnAmount = txnAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "txn_date", length = 19)
	public Date getTxnDate() {
		return txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "txn_id")
	public String getTxnId() {
		return txnId;
	}

	public void setTxnId(String txnId) {
		this.txnId = txnId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "txn_initiate_time", length = 19)
	public Date getTxnInitiateTime() {
		return txnInitiateTime;
	}

	public void setTxnInitiateTime(Date txnInitiateTime) {
		this.txnInitiateTime = txnInitiateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "txn_completion_time", length = 19)
	public Date getTxnCompletionTime() {
		return txnCompletionTime;
	}

	public void setTxnCompletionTime(Date txnCompletionTime) {
		this.txnCompletionTime = txnCompletionTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
