package com.valley.cws.entity;
// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * WcaCategoryDetails generated by hbm2java
 */
@Entity
@Table(name = "WCA_CATEGORY_DETAILS")
public class WcaCategoryDetails implements java.io.Serializable {

	private static final long serialVersionUID = 6838914821938202911L;
	private Long id;
	private String name;
	private Set<WcaSubcategoryDetails> wcaSubcategoryDetailses = new HashSet<WcaSubcategoryDetails>(0);
	private Set<WcaAdData> wcaAdDatas = new HashSet<WcaAdData>(0);
	private Set<CategoryUrlMapping> categoryUrlMappings = new HashSet<>(0);
	private Boolean isInterested;

	public WcaCategoryDetails() {
	}

	public WcaCategoryDetails(String name) {
		this.name = name;
	}

	public WcaCategoryDetails(Long id, String name, Set<WcaSubcategoryDetails> wcaSubcategoryDetailses, Set<WcaAdData> wcaAdDatas,
			Set<CategoryUrlMapping> categoryUrlMappings, Boolean isInterested) {
		super();
		this.id = id;
		this.name = name;
		this.wcaSubcategoryDetailses = wcaSubcategoryDetailses;
		this.wcaAdDatas = wcaAdDatas;
		this.categoryUrlMappings = categoryUrlMappings;
		this.isInterested = isInterested;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_CTGRY_DTL_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaCategoryDetails")
	public Set<WcaSubcategoryDetails> getWcaSubcategoryDetailses() {
		return this.wcaSubcategoryDetailses;
	}

	public void setWcaSubcategoryDetailses(Set<WcaSubcategoryDetails> wcaSubcategoryDetailses) {
		this.wcaSubcategoryDetailses = wcaSubcategoryDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaCategoryDetails")
	public Set<WcaAdData> getWcaAdDatas() {
		return this.wcaAdDatas;
	}

	public void setWcaAdDatas(Set<WcaAdData> wcaAdDatas) {
		this.wcaAdDatas = wcaAdDatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaCategoryDetails")
	public Set<CategoryUrlMapping> getCategoryUrlMappings() {
		return categoryUrlMappings;
	}

	public void setCategoryUrlMappings(Set<CategoryUrlMapping> categoryUrlMappings) {
		this.categoryUrlMappings = categoryUrlMappings;
	}
	
	@Column(name = "is_interested")
	public Boolean getIsInterested() {
	return isInterested;
	}

	public void setIsInterested(Boolean isInterested) {
	this.isInterested = isInterested;
	}

}
