package com.valley.cws.entity;
// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WcaLoginHistory generated by hbm2java
 */
@Entity
@Table(name = "WCA_LOGIN_HISTORY")
public class WcaLoginHistory implements java.io.Serializable {

	private static final long serialVersionUID = -8359370159056201078L;
	private Integer id;
	private WcaUserProfile wcaUserProfile;
	private String nodeMac;
	private String otpUsed;
	private Integer grantDuration;
	private Date createdOn;

	public WcaLoginHistory() {
	}

	public WcaLoginHistory(WcaUserProfile wcaUserProfile) {
		this.wcaUserProfile = wcaUserProfile;
	}

	public WcaLoginHistory(WcaUserProfile wcaUserProfile, String nodeMac, String otpUsed, Integer grantDuration,
			Date createdOn) {
		this.wcaUserProfile = wcaUserProfile;
		this.nodeMac = nodeMac;
		this.otpUsed = otpUsed;
		this.grantDuration = grantDuration;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_LGN_HSTRY_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public WcaUserProfile getWcaUserProfile() {
		return this.wcaUserProfile;
	}

	public void setWcaUserProfile(WcaUserProfile wcaUserProfile) {
		this.wcaUserProfile = wcaUserProfile;
	}

	@Column(name = "node_mac", length = 45)
	public String getNodeMac() {
		return this.nodeMac;
	}

	public void setNodeMac(String nodeMac) {
		this.nodeMac = nodeMac;
	}

	@Column(name = "otp_used", length = 45)
	public String getOtpUsed() {
		return this.otpUsed;
	}

	public void setOtpUsed(String otpUsed) {
		this.otpUsed = otpUsed;
	}

	@Column(name = "grant_duration")
	public Integer getGrantDuration() {
		return this.grantDuration;
	}

	public void setGrantDuration(Integer grantDuration) {
		this.grantDuration = grantDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
