package com.valley.cws.entity;


//Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* WcaPolicyAdConfiguration generated by hbm2java
*/
@Entity
@Table(name = "WCA_POLICY_AD_CONFIGURATION")
public class WcaPolicyAdConfiguration implements java.io.Serializable, Comparable<WcaPolicyAdConfiguration> {

	private static final long serialVersionUID = -3350906931358008802L;
	private Long id;
	private WcaAdData wcaAdData;
	private WcaAdData wcaAdData1;
	private WcaAdData wcaAdData2;
	private WcaAdData wcaAdData3;
	private WcaPolicyConfiguration wcaPolicyConfiguration;
	private Date startTime;
	private Date endTime;
	private Integer priority;
	private Integer freeMinutes;
	private String adType;
	private String adType1;
	private String adType2;
	private String adType3;
	private String screenType;

	public WcaPolicyAdConfiguration() {
	}

	public WcaPolicyAdConfiguration(WcaAdData wcaAdData, WcaPolicyConfiguration wcaPolicyConfiguration) {
		this.wcaAdData = wcaAdData;
		this.wcaPolicyConfiguration = wcaPolicyConfiguration;
	}

	public WcaPolicyAdConfiguration(Long id, WcaAdData wcaAdData, WcaAdData wcaAdData1, WcaAdData wcaAdData2, WcaAdData wcaAdData3,
			WcaPolicyConfiguration wcaPolicyConfiguration, Date startTime, Date endTime, Integer priority, Integer freeMinutes,
			String adType, String adType1, String adType2, String adType3, String screenType) {
		super();
		this.id = id;
		this.wcaAdData = wcaAdData;
		this.wcaAdData1 = wcaAdData1;
		this.wcaAdData2 = wcaAdData2;
		this.wcaAdData3 = wcaAdData3;
		this.wcaPolicyConfiguration = wcaPolicyConfiguration;
		this.startTime = startTime;
		this.endTime = endTime;
		this.priority = priority;
		this.freeMinutes = freeMinutes;
		this.adType = adType;
		this.adType1 = adType1;
		this.adType2 = adType2;
		this.adType3 = adType3;
		this.screenType = screenType;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_PLCY_AD_CNFGRTN_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ad_id", nullable = false)
	public WcaAdData getWcaAdData() {
		return this.wcaAdData;
	}

	public void setWcaAdData(WcaAdData wcaAdData) {
		this.wcaAdData = wcaAdData;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ad_id1", nullable = false)
	public WcaAdData getWcaAdData1() {
		return this.wcaAdData1;
	}

	public void setWcaAdData1(WcaAdData wcaAdData1) {
		this.wcaAdData1 = wcaAdData1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ad_id2", nullable = false)
	public WcaAdData getWcaAdData2() {
		return this.wcaAdData2;
	}

	public void setWcaAdData2(WcaAdData wcaAdData2) {
		this.wcaAdData2 = wcaAdData2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ad_id3", nullable = false)
	public WcaAdData getWcaAdData3() {
		return this.wcaAdData3;
	}

	public void setWcaAdData3(WcaAdData wcaAdData3) {
		this.wcaAdData3 = wcaAdData3;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "policy_id", nullable = false)
	public WcaPolicyConfiguration getWcaPolicyConfiguration() {
		return this.wcaPolicyConfiguration;
	}

	public void setWcaPolicyConfiguration(WcaPolicyConfiguration wcaPolicyConfiguration) {
		this.wcaPolicyConfiguration = wcaPolicyConfiguration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "ad_type", length = 45)
	public String getAdType() {
		return this.adType;
	}

	public void setAdType(String adType) {
		this.adType = adType;
	}

	@Column(name = "ad_type1")
	public String getAdType1() {
	return adType1;
	}

	public void setAdType1(String adType1) {
	this.adType1 = adType1;
	}

	@Column(name = "ad_type2")
	public String getAdType2() {
	return adType2;
	}

	public void setAdType2(String adType2) {
	this.adType2 = adType2;
	}

	@Column(name = "ad_type3")
	public String getAdType3() {
	return adType3;
	}

	public void setAdType3(String adType3) {
	this.adType3 = adType3;
	}

	@Column(name = "screen_type")
	public String getScreenType() {
	return screenType;
	}

	public void setScreenType(String screenType) {
	this.screenType = screenType;
	}



	@Column(name = "free_minutes")
	public Integer getFreeMinutes() {
		return freeMinutes;
	}

	public void setFreeMinutes(Integer freeMinutes) {
		this.freeMinutes = freeMinutes;
	}

	@Override
	public int compareTo(WcaPolicyAdConfiguration o) {
		return (this.priority < o.priority ? -1 : (this.priority == o.priority) ? 0 : 1);
	}

}
