package com.valley.cws.entity;
// Generated Aug 9, 2016 10:46:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WcaPolicyPeriod generated by hbm2java
 */
@Entity
@Table(name = "WCA_POLICY_PERIOD")
public class WcaPolicyPeriod implements java.io.Serializable {

	private static final long serialVersionUID = 8906038876741565779L;
	private Long id;
	private Boolean hour;
	private Date hourFrom;
	private Date hourTo;
	private Boolean day;
	private String dayValue;
	private Boolean date;
	private Date dateFrom;
	private Date dateTo;
	private Boolean weekend;
	private String weekendValue;
	private Boolean week;
	private String weekFrom;
	private String weekTo;
	private Boolean month;
	private String monthValue;
	private Boolean year;
	private String yearValue;
	private Set<WcaPolicyConfiguration> wcaPolicyConfigurations = new HashSet<WcaPolicyConfiguration>(0);

	public WcaPolicyPeriod() {
	}

	public WcaPolicyPeriod(Boolean hour, Date hourFrom, Date hourTo, Boolean day, String dayValue, Boolean date,
			Date dateFrom, Date dateTo, Boolean weekend, String weekendValue, Boolean week, String weekFrom,
			String weekTo, Boolean month, String monthValue, Boolean year, String yearValue,
			Set<WcaPolicyConfiguration> wcaPolicyConfigurations) {
		this.hour = hour;
		this.hourFrom = hourFrom;
		this.hourTo = hourTo;
		this.day = day;
		this.dayValue = dayValue;
		this.date = date;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.weekend = weekend;
		this.weekendValue = weekendValue;
		this.week = week;
		this.weekFrom = weekFrom;
		this.weekTo = weekTo;
		this.month = month;
		this.monthValue = monthValue;
		this.year = year;
		this.yearValue = yearValue;
		this.wcaPolicyConfigurations = wcaPolicyConfigurations;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_PLCY_PRD_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "hour_")
	public Boolean getHour() {
		return this.hour;
	}

	public void setHour(Boolean hour) {
		this.hour = hour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hour_from", length = 19)
	public Date getHourFrom() {
		return this.hourFrom;
	}

	public void setHourFrom(Date hourFrom) {
		this.hourFrom = hourFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hour_to", length = 19)
	public Date getHourTo() {
		return this.hourTo;
	}

	public void setHourTo(Date hourTo) {
		this.hourTo = hourTo;
	}

	@Column(name = "day_")
	public Boolean getDay() {
		return this.day;
	}

	public void setDay(Boolean day) {
		this.day = day;
	}

	@Column(name = "day_value", length = 65535)
	public String getDayValue() {
		return this.dayValue;
	}

	public void setDayValue(String dayValue) {
		this.dayValue = dayValue;
	}

	@Column(name = "date_")
	public Boolean getDate() {
		return this.date;
	}

	public void setDate(Boolean date) {
		this.date = date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	@Column(name = "weekend")
	public Boolean getWeekend() {
		return this.weekend;
	}

	public void setWeekend(Boolean weekend) {
		this.weekend = weekend;
	}

	@Column(name = "weekend_value", length = 45)
	public String getWeekendValue() {
		return this.weekendValue;
	}

	public void setWeekendValue(String weekendValue) {
		this.weekendValue = weekendValue;
	}

	@Column(name = "week")
	public Boolean getWeek() {
		return this.week;
	}

	public void setWeek(Boolean week) {
		this.week = week;
	}

	@Column(name = "week_from", length = 45)
	public String getWeekFrom() {
		return this.weekFrom;
	}

	public void setWeekFrom(String weekFrom) {
		this.weekFrom = weekFrom;
	}

	@Column(name = "week_to", length = 45)
	public String getWeekTo() {
		return this.weekTo;
	}

	public void setWeekTo(String weekTo) {
		this.weekTo = weekTo;
	}

	@Column(name = "month")
	public Boolean getMonth() {
		return this.month;
	}

	public void setMonth(Boolean month) {
		this.month = month;
	}

	@Column(name = "month_value")
	public String getMonthValue() {
		return this.monthValue;
	}

	public void setMonthValue(String monthValue) {
		this.monthValue = monthValue;
	}

	@Column(name = "year")
	public Boolean getYear() {
		return this.year;
	}

	public void setYear(Boolean year) {
		this.year = year;
	}

	@Column(name = "year_value", length = 45)
	public String getYearValue() {
		return this.yearValue;
	}

	public void setYearValue(String yearValue) {
		this.yearValue = yearValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaPolicyPeriod")
	public Set<WcaPolicyConfiguration> getWcaPolicyConfigurations() {
		return this.wcaPolicyConfigurations;
	}

	public void setWcaPolicyConfigurations(Set<WcaPolicyConfiguration> wcaPolicyConfigurations) {
		this.wcaPolicyConfigurations = wcaPolicyConfigurations;
	}

}
