package com.valley.cws.entity;

// Generated Aug 9, 2016 10:11:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * WcaUserProfile generated by hbm2java
 */
@Entity
@Table(name = "WCA_USER_PROFILE")
public class WcaUserProfile implements java.io.Serializable {

	private static final long serialVersionUID = 920819428540602239L;
	private Integer id;
	private String macAddress;
	private String userName;
	private String emailId;
	private String mobileNo;
	private String deviceId;
	private String softwareVersion;
	private String phoneType;
	private String country;
	private String operatorName;
	private String operatorCode;
	private String simSerialNo;
	private String deviceModel;
	private String osVersion;
	private String apiLevel;
	private String deviceName;
	private String product;
	private String manufacturerName;
	private String primaryCategory;
	private String secondaryCategory;
	private String ternaryCategory;
	private String lastOtp;
	private String ipV4;
	private String ssid;
	private String bssid;
	private String signalStrength;
	private String frequency;
	private String channelNumber;
	private String linkSpeed;
	private String rssi;
	private String ipAddress;
	private String dns1;
	private String dns2;
	private String gateway;
	private String leaseDuration;
	private String netMask;
	private String serverAddress;
	private String nodeMac;
	private String clientIp;
	private String baseGrantUrl;
	private String continueUrl;
	private String accessPoint;
	private String location;
	private String gender;
	private String address;
	private String city;
	private String state;
	private String apName;
	private String apTags;
	private String gcmRegId;
	private Integer pinCode;
	private byte[] profileImage;
	private Integer adShownCount;
	private Integer imageCounter;
	private Integer videoCounter;
	private Integer audioCounter;
	private Integer walletPoint;
	private String resolutionType;
	private Integer singleAdCounter;
	private Date dob;
	private Date createdOn;
	private Date updatedOn;
	private Date expiryDate;
	private Date startDate;
	private Set<WcaBrowsingHistory> wcaBrowsingHistories = new HashSet<WcaBrowsingHistory>(0);
	private Set<WcaRunningAppHistory> wcaRunningAppHistories = new HashSet<WcaRunningAppHistory>(0);
	private Set<WcaAppDataUsage> wcaAppDataUsages = new HashSet<WcaAppDataUsage>(0);
	private Set<WcaBuyingHistory> wcaBuyingHistories = new HashSet<WcaBuyingHistory>(0);
	private Set<WcaAdShownHistory> wcaAdShownHistories = new HashSet<WcaAdShownHistory>(0);
	private Set<WcaLoginHistory> wcaLoginHistories = new HashSet<WcaLoginHistory>(0);
	private Set<WcaUserInterest> wcaUserInterests = new HashSet<WcaUserInterest>(0);

	public WcaUserProfile() {
	}

	public WcaUserProfile(Integer id, String macAddress, String userName, String emailId, String mobileNo,
			String deviceId, String softwareVersion, String phoneType, String country, String operatorName,
			String operatorCode, String simSerialNo, String deviceModel, String osVersion, String apiLevel,
			String deviceName, String product, String manufacturerName, String primaryCategory,
			String secondaryCategory, String ternaryCategory, String lastOtp, String ipV4, String ssid, String bssid,
			String signalStrength, String frequency, String channelNumber, String linkSpeed, String rssi,
			String ipAddress, String dns1, String dns2, String gateway, String leaseDuration, String netMask,
			String serverAddress, String nodeMac, String clientIp, String baseGrantUrl, String continueUrl,
			String accessPoint, String location, String gender, String address, String city, String state,
			String apName, String apTags, String gcmRegId, Integer pinCode, byte[] profileImage, Integer adShownCount,
			Integer imageCounter, Integer videoCounter, Integer audioCounter, Integer walletPoint,
			String resolutionType, Integer singleAdCounter, Date dob, Date createdOn, Date updatedOn, Date expiryDate,
			Date startDate, Set<WcaBrowsingHistory> wcaBrowsingHistories,
			Set<WcaRunningAppHistory> wcaRunningAppHistories, Set<WcaAppDataUsage> wcaAppDataUsages,
			Set<WcaBuyingHistory> wcaBuyingHistories, Set<WcaAdShownHistory> wcaAdShownHistories,
			Set<WcaLoginHistory> wcaLoginHistories) {
		super();
		this.id = id;
		this.macAddress = macAddress;
		this.userName = userName;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.deviceId = deviceId;
		this.softwareVersion = softwareVersion;
		this.phoneType = phoneType;
		this.country = country;
		this.operatorName = operatorName;
		this.operatorCode = operatorCode;
		this.simSerialNo = simSerialNo;
		this.deviceModel = deviceModel;
		this.osVersion = osVersion;
		this.apiLevel = apiLevel;
		this.deviceName = deviceName;
		this.product = product;
		this.manufacturerName = manufacturerName;
		this.primaryCategory = primaryCategory;
		this.secondaryCategory = secondaryCategory;
		this.ternaryCategory = ternaryCategory;
		this.lastOtp = lastOtp;
		this.ipV4 = ipV4;
		this.ssid = ssid;
		this.bssid = bssid;
		this.signalStrength = signalStrength;
		this.frequency = frequency;
		this.channelNumber = channelNumber;
		this.linkSpeed = linkSpeed;
		this.rssi = rssi;
		this.ipAddress = ipAddress;
		this.dns1 = dns1;
		this.dns2 = dns2;
		this.gateway = gateway;
		this.leaseDuration = leaseDuration;
		this.netMask = netMask;
		this.serverAddress = serverAddress;
		this.nodeMac = nodeMac;
		this.clientIp = clientIp;
		this.baseGrantUrl = baseGrantUrl;
		this.continueUrl = continueUrl;
		this.accessPoint = accessPoint;
		this.location = location;
		this.gender = gender;
		this.address = address;
		this.city = city;
		this.state = state;
		this.apName = apName;
		this.apTags = apTags;
		this.gcmRegId = gcmRegId;
		this.pinCode = pinCode;
		this.profileImage = profileImage;
		this.adShownCount = adShownCount;
		this.imageCounter = imageCounter;
		this.videoCounter = videoCounter;
		this.audioCounter = audioCounter;
		this.walletPoint = walletPoint;
		this.resolutionType = resolutionType;
		this.singleAdCounter = singleAdCounter;
		this.dob = dob;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.expiryDate = expiryDate;
		this.startDate = startDate;
		this.wcaBrowsingHistories = wcaBrowsingHistories;
		this.wcaRunningAppHistories = wcaRunningAppHistories;
		this.wcaAppDataUsages = wcaAppDataUsages;
		this.wcaBuyingHistories = wcaBuyingHistories;
		this.wcaAdShownHistories = wcaAdShownHistories;
		this.wcaLoginHistories = wcaLoginHistories;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@SequenceGenerator(name = "id_Sequence", sequenceName = "WCA_USR_PRFL_ID_SEQ", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mac_address", length = 45)
	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email_id", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobile_no", length = 45)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "device_id", length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "software_version", length = 45)
	public String getSoftwareVersion() {
		return this.softwareVersion;
	}

	public void setSoftwareVersion(String softwareVersion) {
		this.softwareVersion = softwareVersion;
	}

	@Column(name = "phone_type", length = 45)
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "operator_name", length = 45)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "operator_code", length = 45)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	@Column(name = "sim_serial_no", length = 45)
	public String getSimSerialNo() {
		return this.simSerialNo;
	}

	public void setSimSerialNo(String simSerialNo) {
		this.simSerialNo = simSerialNo;
	}

	@Column(name = "device_model", length = 45)
	public String getDeviceModel() {
		return this.deviceModel;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	@Column(name = "os_version", length = 45)
	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	@Column(name = "api_level", length = 45)
	public String getApiLevel() {
		return this.apiLevel;
	}

	public void setApiLevel(String apiLevel) {
		this.apiLevel = apiLevel;
	}

	@Column(name = "device_name", length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "product", length = 45)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "manufacturer_name", length = 45)
	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	@Column(name = "primary_category", length = 45)
	public String getPrimaryCategory() {
		return this.primaryCategory;
	}

	public void setPrimaryCategory(String primaryCategory) {
		this.primaryCategory = primaryCategory;
	}

	@Column(name = "secondary_category", length = 45)
	public String getSecondaryCategory() {
		return this.secondaryCategory;
	}

	public void setSecondaryCategory(String secondaryCategory) {
		this.secondaryCategory = secondaryCategory;
	}

	@Column(name = "ternary_category", length = 45)
	public String getTernaryCategory() {
		return this.ternaryCategory;
	}

	public void setTernaryCategory(String ternaryCategory) {
		this.ternaryCategory = ternaryCategory;
	}

	@Column(name = "last_otp", length = 45)
	public String getLastOtp() {
		return this.lastOtp;
	}

	public void setLastOtp(String lastOtp) {
		this.lastOtp = lastOtp;
	}

	@Column(name = "ip_v4")
	public String getIpV4() {
		return ipV4;
	}

	public void setIpV4(String ipV4) {
		this.ipV4 = ipV4;
	}

	@Column(name = "ssid")
	public String getSsid() {
		return ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	@Column(name = "bssid")
	public String getBssid() {
		return bssid;
	}

	public void setBssid(String bssid) {
		this.bssid = bssid;
	}

	@Column(name = "signal_strength")
	public String getSignalStrength() {
		return signalStrength;
	}

	public void setSignalStrength(String signalStrength) {
		this.signalStrength = signalStrength;
	}

	@Column(name = "frequency")
	public String getFrequency() {
		return frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "channel_number")
	public String getChannelNumber() {
		return channelNumber;
	}

	public void setChannelNumber(String channelNumber) {
		this.channelNumber = channelNumber;
	}

	@Column(name = "link_speed")
	public String getLinkSpeed() {
		return linkSpeed;
	}

	public void setLinkSpeed(String linkSpeed) {
		this.linkSpeed = linkSpeed;
	}

	@Column(name = "rssi")
	public String getRssi() {
		return rssi;
	}

	public void setRssi(String rssi) {
		this.rssi = rssi;
	}

	@Column(name = "ip_address")
	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "dns_1")
	public String getDns1() {
		return dns1;
	}

	public void setDns1(String dns1) {
		this.dns1 = dns1;
	}

	@Column(name = "dns_2")
	public String getDns2() {
		return dns2;
	}

	public void setDns2(String dns2) {
		this.dns2 = dns2;
	}

	@Column(name = "gateway")
	public String getGateway() {
		return gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	@Column(name = "lease_duration")
	public String getLeaseDuration() {
		return leaseDuration;
	}

	public void setLeaseDuration(String leaseDuration) {
		this.leaseDuration = leaseDuration;
	}

	@Column(name = "net_mask")
	public String getNetMask() {
		return netMask;
	}

	public void setNetMask(String netMask) {
		this.netMask = netMask;
	}

	@Column(name = "server_address")
	public String getServerAddress() {
		return serverAddress;
	}

	public void setServerAddress(String serverAddress) {
		this.serverAddress = serverAddress;
	}

	@Column(name = "node_mac")
	public String getNodeMac() {
		return nodeMac;
	}

	public void setNodeMac(String nodeMac) {
		this.nodeMac = nodeMac;
	}

	@Column(name = "client_ip")
	public String getClientIp() {
		return clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	@Column(name = "base_grant_url")
	public String getBaseGrantUrl() {
		return baseGrantUrl;
	}

	public void setBaseGrantUrl(String baseGrantUrl) {
		this.baseGrantUrl = baseGrantUrl;
	}

	@Column(name = "continue_url")
	public String getContinueUrl() {
		return continueUrl;
	}

	public void setContinueUrl(String continueUrl) {
		this.continueUrl = continueUrl;
	}

	@Column(name = "access_point")
	public String getAccessPoint() {
		return accessPoint;
	}

	public void setAccessPoint(String accessPoint) {
		this.accessPoint = accessPoint;
	}

	@Column(name = "location")
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "ad_shown_count")
	public Integer getAdShownCount() {
		return adShownCount;
	}

	public void setAdShownCount(Integer adShownCount) {
		this.adShownCount = adShownCount;
	}

	@Column(name = "image_counter")
	public Integer getImageCounter() {
		return imageCounter;
	}

	public void setImageCounter(Integer imageCounter) {
		this.imageCounter = imageCounter;
	}

	@Column(name = "video_counter")
	public Integer getVideoCounter() {
		return videoCounter;
	}

	public void setVideoCounter(Integer videoCounter) {
		this.videoCounter = videoCounter;
	}

	@Column(name = "audio_counter")
	public Integer getAudioCounter() {
		return audioCounter;
	}

	public void setAudioCounter(Integer audioCounter) {
		this.audioCounter = audioCounter;
	}

	@Column(name = "gender")
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "address")
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "profile_image")
	public byte[] getProfileImage() {
		return profileImage;
	}

	public void setProfileImage(byte[] profileImage) {
		this.profileImage = profileImage;
	}

	@Column(name = "city")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "gcm_reg_id")
	public String getGcmRegId() {
		return gcmRegId;
	}

	public void setGcmRegId(String gcmRegId) {
		this.gcmRegId = gcmRegId;
	}

	@Column(name = "pin_code")
	public Integer getPinCode() {
		return pinCode;
	}

	public void setPinCode(Integer pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "wallet_point")
	public Integer getWalletPoint() {
		return walletPoint;
	}

	public void setWalletPoint(Integer walletPoint) {
		this.walletPoint = walletPoint;
	}

	@Column(name = "resolution_type")
	public String getResolutionType() {
		return resolutionType;
	}

	public void setResolutionType(String resolutionType) {
		this.resolutionType = resolutionType;
	}

	@Column(name = "ap_name")
	public String getApName() {
		return apName;
	}

	public void setApName(String apName) {
		this.apName = apName;
	}

	@Column(name = "ap_tags")
	public String getApTags() {
		return apTags;
	}

	public void setApTags(String apTags) {
		this.apTags = apTags;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 19)
	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "single_ad_counter")
	public Integer getSingleAdCounter() {
		return singleAdCounter;
	}

	public void setSingleAdCounter(Integer singleAdCounter) {
		this.singleAdCounter = singleAdCounter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 19)
	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaBrowsingHistory> getWcaBrowsingHistories() {
		return this.wcaBrowsingHistories;
	}

	public void setWcaBrowsingHistories(Set<WcaBrowsingHistory> wcaBrowsingHistories) {
		this.wcaBrowsingHistories = wcaBrowsingHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaRunningAppHistory> getWcaRunningAppHistories() {
		return wcaRunningAppHistories;
	}

	public void setWcaRunningAppHistories(Set<WcaRunningAppHistory> wcaRunningAppHistories) {
		this.wcaRunningAppHistories = wcaRunningAppHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaBuyingHistory> getWcaBuyingHistories() {
		return this.wcaBuyingHistories;
	}

	public void setWcaBuyingHistories(Set<WcaBuyingHistory> wcaBuyingHistories) {
		this.wcaBuyingHistories = wcaBuyingHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaAdShownHistory> getWcaAdShownHistories() {
		return this.wcaAdShownHistories;
	}

	public void setWcaAdShownHistories(Set<WcaAdShownHistory> wcaAdShownHistories) {
		this.wcaAdShownHistories = wcaAdShownHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaLoginHistory> getWcaLoginHistories() {
		return this.wcaLoginHistories;
	}

	public void setWcaLoginHistories(Set<WcaLoginHistory> wcaLoginHistories) {
		this.wcaLoginHistories = wcaLoginHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaAppDataUsage> getWcaAppDataUsages() {
		return wcaAppDataUsages;
	}

	public void setWcaAppDataUsages(Set<WcaAppDataUsage> wcaAppDataUsages) {
		this.wcaAppDataUsages = wcaAppDataUsages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wcaUserProfile")
	@Cascade(CascadeType.DELETE)
	public Set<WcaUserInterest> getWcaUserInterests() {
		return wcaUserInterests;
	}

	public void setWcaUserInterests(Set<WcaUserInterest> wcaUserInterests) {
		this.wcaUserInterests = wcaUserInterests;
	}
}
